### ISSUE TITLE
examples for new yaml structure

### ISSUE THREAD

**Issue by shahzebsiddiqui** [HPC-buildtest/buildtest-framework#135]
**OpenMP example using gnu and intel**

Description: This test should compile *hello.c* with gnu and intel compiler using ``OMP_NUM_THREADS=2``

```
scheduler: local
compile: yes
matrix: 
  env:
    - OMP_NUM_THREADS=2
  compilers:
   - gnu
   - intel

pre_build:
  - echo "pre build commands"
  - time

build:
  src: hello.c
  gnu: 
    cflags: -O2 -fopenmp
  intel:
    cflags: -O2 -fopenmp

post_build:
  - echo "post build command"
  - time  
```

**Test without a build**
Description: This test is just running shell commands without any compilation
```
compile: no
run:
  - time
  - mpirun -np 2 osu_gather
  - time
```

**Multiple Compilation Flags with gnu and intel compiler**
Description: hello.c will be compiled with gnu and intel compiler with two combination for cflags for gnu and intel totaling 4 compilations
```
compile: yes
matrix:
  compiler:
    - gnu
   - intel
  cflags:
    gnu:
      - "-O2 --fast"
      - "-O3"
   intel:
     - "-O2 --fma"
    - "-O1 -g"
build:
  src: hello.c
```
